channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1.1
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - graphviz==0.21
  - lightgbm==4.6.0
  - matplotlib==3.10.8
  - numpy==2.4.1
  - pandas==2.3.3
  - psutil==7.2.1
  - pyarrow==22.0.0
  - scikit-learn==1.8.0
  - scipy==1.17.0
name: mlflow-env
